{% set name = "capnproto" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/capnproto/capnproto/archive/v{{ version }}.tar.gz
  sha256: d5ebdf858e9885c33d4b3f765006d68bd66e9b002bf4d607ff4317ef9c1aac6a
  patches:
    # MSVC miscompiles async.c++ file when /O2 is given
    - patches/fix-msvc.diff

build:
  number: 0
  run_exports:
    # soname changes with every release
    # https://abi-laboratory.pro/index.php?view=timeline&l=capnproto
    - {{ pin_subpackage('capnproto', max_pin='x.x.x') }}
  ignore_prefix_files:
    - bin/capnp

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make  # [not win]
    - sed   # [osx]
    - gawk  # [osx]
    - automake   # [unix]
    - autoconf   # [unix]
    - libtool    # [unix]
    - llvm-tools  # [osx]
  host:
    - zlib {{ zlib }}
    - openssl {{ openssl }}
  run:
    - openssl  # exact pin handled through openssl run_exports

test:
  commands:
    - capnp --help
    - capnpc --help
    - capnpc-c++ --help
    - capnpc-capnp --help

    - test -d "$PREFIX/include/capnp"  # [unix]
    - if not exist %LIBRARY_INC%\\capnp exit 1  # [win]

    - test -f "$PREFIX/lib/libcapnp${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnp-rpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj-async${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_LIB%\\capnp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kj.lib exit 1  # [win]

about:
  home: https://capnproto.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: An insanely fast data interchange format and capability-based RPC system.
  description: >
    Cap'n Proto is an insanely fast data interchange format and capability-based RPC system.
    Think JSON, except binary. Or think Protocol Buffers, except faster. In fact, in benchmarks,
    Cap'n Proto is INFINITY TIMES faster than Protocol Buffers.
  dev_url: https://github.com/capnproto/capnproto
  doc_url: https://capnproto.org

extra:
  recipe-maintainers:
    - LehMaxence
    - ihnorton
    - Shelnutt2
