{% set version = "0.10.4" %}

package:
  name: capnproto
  version: {{ version }}

source:
  url: https://capnproto.org/capnproto-c++-{{ version }}.tar.gz
  sha256: 981e7ef6dbe3ac745907e55a78870fbb491c5d23abd4ebc04e20ec235af4458c

build:
  number: 0
  run_exports:
    # soname changes with every release
    # https://abi-laboratory.pro/index.php?view=timeline&l=capnproto
    - {{ pin_subpackage('capnproto', max_pin='x.x.x') }}
  ignore_prefix_files:
    - bin/capnp
  missing_dso_whitelist:  # [linux]
    - $RPATH/ld64.so.1    # [linux]

requirements:
  build:
    - cmake  # [win]
    - make  # [not win]
    - sed   # [osx]
    - gawk  # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake   # [unix]
    - autoconf   # [unix]
    - libtool    # [unix]
    - llvm-tools  # [osx]
  host:
    - zlib
    - openssl {{ openssl }}
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - openssl 3.*

test:
  commands:
    - capnp --help
    - capnpc --help
    - capnpc-c++ --help
    - capnpc-capnp --help

    - test -d "$PREFIX/include/capnp"  # [unix]
    - if not exist %LIBRARY_INC%\\capnp exit 1  # [win]

    - test -f "$PREFIX/lib/libcapnp${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnp-rpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj-async${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_LIB%\\capnp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kj.lib exit 1  # [win]

about:
  home: https://capnproto.org
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: An insanely fast data interchange format and capability-based RPC system.
  description: >
    Cap'n Proto is an insanely fast data interchange format and capability-based RPC system.
    Think JSON, except binary. Or think Protocol Buffers, except faster. In fact, in benchmarks,
    Cap'n Proto is INFINITY TIMES faster than Protocol Buffers.
  dev_url: https://github.com/capnproto/capnproto
  doc_url: https://capnproto.org

extra:
  recipe-maintainers:
    - LehMaxence
    - ihnorton
    - Shelnutt2
