travis:
  secure:
    BINSTAR_TOKEN: wJo1keXwcvTyGOIzPduXWryQaEEfM06k5pugcI6S4+PEn/r1KGRtE3qsWchy2IMHngt6zR0D0r+8KyHbsYneoO4aN/oF3wX+Oia7xx07176JSb0bRA/eS5+qqNaH4vHa/84zci0B3kVselB6YgSdcOzM0H+8zZVcBTNeR4d7U0DqsU5IZg6IKSGviqXWv4BRZ7E4t4Nn1KQ/K7QopjvmJV5RvZjxg7Ghq9K0hIq/lvP85/y0jYQIkPzjGKuV3nPHdwuNW5bJLIJQ5geozFsO2e+1CO/JhJMSV899H3qwazNbxOviIJ3Wzq0k6bkxKcCEjcNYBk3xWuOMHbwsb2JQFkStvwfcGQ+2qoOeIpsg5C3+Q24fNPBr1/Sqx6D4i0z59vNm+AiAjJ5K+mn+F7CAYLiGVdUNFkYDZkooR48wwhw0yHsj+m/LEcQElWDGaeotFeBDH90MOO8Jxxkh9zwr+JxyM29m0v8ETniqvX+RARwZmp3J2OdxkHaofAucdryAbN6XPDJ5Q56z4mpeF2Naye1K3LtEhhBKbmO3yEz8w3w2FpJMa0J2Pkt5yy4GIpH8AToamjrnVhIjsEq1bTorPH43Z0AGEt0SfzyPM/pkeA+6ULU/lOojwcGrlJ2kGJeeORSnbBfaetN9RBnM3PVQuI45tmHbAg6T0kDwTHrc7DA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
