travis:
  secure:
    BINSTAR_TOKEN: W63JOn4q5+Zh4TAUCtx6FMRCmB7wflT8QdKzHXpcKTbr30FSfS44xXLoIr5KTSDD8+Y3Onb3Qqv8kd2zUoBzIsAwpXjm8gx2hcTGzVT+QxalvlWtoYQs9u46rAdn31WXfgjcKp3xGeHqc0PKZu7iqQuel9e+QSLtiuHjf4Pl58wEfgoaG8lX5Afxefzi/cEvNZYKBvcxeTO+Stm8PsJlYy/SaKWb9XkVzWPDY9fExOQBXN1mjyx0RDbpuFOpoY5Sds4v2z+Kz/1UGQkatyUoGG1p8+2zhGJidS417klzV2JqBugTgWaQjSsizUysHbfi5ccLv9+DQvAirN+XaFQjqHGH8ZSlpTFIc4tdRXkZc/nH87UibGtAlWwSoJLV0BlDZ21lrYrTkaWxZ8m1YFR2ZER+Qea1wCvgHlokpxFEzfYtkgdI15XlQB2hBnipznw/b+O87pQJQq5vmZnQZjBR8nntqRdtvqH37pexh6F4TGWLPSxEuiLZ/OmhmrJxNrpY1CP+HMCoc+OW2tTYcLwPxGBCm+Ch2tfpx9dJn4fzvHj9FEArzpsLVj7oTYGgUCDNTBbeIp1Ldc2ZynjMsd+dAymFCZCmcp3HaAD8lMQXb8liNd7gwS2bvMoTGJsTGqDPz6+LyAlqPzOoxB6XdpvZSc1q6eicE9j1fAK7Uwj/A7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
